apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    purpose: dp-demo
spec: 
  replicas: 3 # deployment defination starts from here
  selector:
    matchLabels:
      company: wipro
      employee: dev
  template: # pod defination start from here
    metadata:
      labels:
        company: wipro
        employee: dev
    spec:
      containers:
        - name: nginx
          # image: nginx:1.25.2 # old nginx image for testing
          image: nginx

  