apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  labels:
    DEPLOYMENT_NAME: app
spec: 
  replicas: 3 # deployment defination starts from here
  selector:
    matchLabels:
      DEPLOYMENT_NAME: app
  template: # pod defination start from here
    metadata:
      labels:
       DEPLOYMENT_NAME: app
    spec:
      containers:
        - name: app
          # image: nginx:1.25.2 # old nginx image for testing
          image: nginx

  