name: self hosted runner
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update app
        run: |
          cd ~/app/self-hosted-01
          git pull origin main