name: Dev to Prod Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: [self-hosted, dev-runner]
    environment: DEV

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Dev NGINX
        run: |
          sudo cp .github/workflows/index.html /usr/share/nginx/html/dev/
          sudo systemctl restart nginx

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-dev
    runs-on: [self-hosted, prod-runner]
    environment: PROD

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Prod NGINX
        run: |
          sudo cp .github/workflows/index.html /usr/share/nginx/html/prod/
          sudo systemctl restart nginx
