name: Fundamentals Test
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    name: deploy to Dev
    runs-on: [self-hosted, dev-runner]
    #environment: DEV
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Running on $(hostname)"
          sudo cp index.html /usr/share/nginx/html/
          sudo systemctl restart nginx
  deploy-prod:
    name: deploy to Prod
    needs: deploy-dev
    runs-on: [self-hosted, prod-runner]
    environment: PROD
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo cp index.html /usr/share/nginx/html/
          sudo systemctl restart nginx      