name: Fundamentals Test
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    name: deploy to Dev
    runs-on: [self-hosted, dev-runner]
    environment: DEV
    steps:
      name: Checkout from main
      uses: actions/checkout@v1

      name: Deploy DEV nginx
      run: |
        sudo cp .github/workflows/index.html /usr/share/nginx/html/dev/
        sudo systemctl restart nginx
  deploy-prod:
    name: deploy to Prod
    runs-on: [self-hosted, prod-runner]
    environment: PROD
    steps:
      name: Checkout from main
      uses: actions/checkout@v1

      name: Deploy to PROD nginx
      run: |
        sudo cp .github/workflows/index.html /usr/share/nginx/html/prod/
        sudo systemctl restart nginx      