#Build → Test → Deploy
name: Pipeline Flow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building app..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing app..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying app..."
