name: Deploy to EKS REPO
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repo C
      - name: Checkout pipeline repo
        uses: actions/checkout@v3

      # Checkout Repo B (k8s manifests )
      - name: Checkout k8s repo
        uses: actions/checkout@v3
        with:
          repository: KiranBKittu/Kubernetes
          uses: :contentReference[oaicite:0]{index=0}@v3
          token: ${{ secrets.GITHUB_TOKEN }} # no need to mention any where
          path: k8s

      # Configure AWS details
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Connect to EKS cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      # Deploy to Kubernetes
      - name: Apply manifests
        run: |
          kubectl apply -f k8s/20-deployment.yml
