# before running this we have to run deployment of k8s which is having below deployment & conainer name matched
#after that if we run this no need to run deployment again Kubernetes rolling update
name: Build and Push Docker Image
on: push
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: app # ECR Repository name
  CLUSTER_NAME: Test12345 #Cluster name
  DEPLOYMENT_NAME: app # this app and metadata labels of deployment should match 
  CONTAINER_NAME: app #This must match the container name inside the deployment:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Commit id as small i.e 7 letters
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t my-app:$SHORT_SHA ./app

      - name: Tag image for ECR
        run: docker tag my-app:$SHORT_SHA 683134746681.dkr.ecr.us-east-1.amazonaws.com/app:$SHORT_SHA

      - name: Push image to ECR
        run: docker push 683134746681.dkr.ecr.us-east-1.amazonaws.com/app:$SHORT_SHA# Update kubeconfig

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
        
      # Deploy new image
      - name: Deploy to EKS
        run: kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=683134746681.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$SHORT_SHA
